### PR TITLE
Add support for VK_KHR_driver_properties

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Thx for this PR, great job!

Looks good to me. I'll try to take a look at it this weekend and merge this.

**Comment by SaschaWillems** [comment]
@krOoze: Can you check if this compiles for the Android target? I'm getting template specialization errors and also to_string is missing from the std namespace on Android.

**Comment by krOoze** [comment]
@SaschaWillems Yea that's familiar. Old NDK would do that; it lacks proper stl support.

**Comment by SaschaWillems** [comment]
Looks like my Qt installation is still using NDK r16. Will try with r18.

**Comment by krOoze** [comment]
I used only VS, I will try Qt creator then to build.

**Comment by krOoze** [comment]
@SaschaWillems Ok, hopefully solved by #53

**Pull request merged**
