### PR TITLE
Do not include libwayland-client.so within AppImage for Linux/Wayland.

### PR DESCRIPTION
**Pull request by codecnotsupported**
#171 (probably) has a small typo.
Hopefully it works this time.

### CODE REVIEW

**Comment by firescry** [comment]
Hello @codecnotsupported, I also see that the latest binary (3.31) published on https://vulkan.gpuinfo.org/download.php contains wayland library:
> $ ./vulkancapsviewer_3.31_linux64_wayland.AppImage --appimage-extract | grep wayland
> squashfs-root/usr/lib/libwayland-client.so.0
> $

and it still doesn't work.

But when I rebuild the same code in GitHub, the appimage doesn't contain that library and works fine:
> $ ./Vulkan_Caps_Viewer-wayland-x86_64.AppImage --appimage-extract | grep wayland
> $

The rebuilt app is available here - https://github.com/firescry/VulkanCapsViewer/actions/runs/5168346831. I added only one commit there to upload artifact to GitHub and disable building any other targets that Linux/Wayland. The rest of the code is the same as on master branch here.

@SaschaWillems Are the binaries published on https://gpuinfo.org/ being built by the GitHub CI in this project? Or do you maybe have some separate build flow before publishing?

**Comment by codecnotsupported** [comment]
Can confirm that the CI's rebuild works.
Closing the pull request as @firescry's commit works as intended.
That leaves us with:
> @SaschaWillems Are the binaries published on https://gpuinfo.org/ being built by the GitHub CI in this project? Or do you maybe have some separate build flow before publishing?

**Comment by SaschaWillems** [comment]
> @SaschaWillems Are the binaries published on https://gpuinfo.org/ being built by the GitHub CI in this project? Or do you maybe have some separate build flow before publishing?

The official releases on the download page are taken from tagged version. So these changes will make it there for the next tag.

**Comment by firescry** [comment]
> > @SaschaWillems Are the binaries published on https://gpuinfo.org/ being built by the GitHub CI in this project? Or do you maybe have some separate build flow before publishing?
> 
> The official releases on the download page are taken from tagged version. So these changes will make it there for the next tag.

I confirm that the correction found it's way to official binaries for version `3.32` release and it works for me under Wayland. Thanks! 😊

**Pull request closed without merging**
