### PR TITLE
Fix Wayland build

### PR DESCRIPTION
**Pull request by emersion**
Two issues, see individual commits.

### CODE REVIEW

**Comment by emersion** [comment]
Ah, that first commit is exactly https://github.com/SaschaWillems/VulkanCapsViewer/pull/154.

**Comment by SaschaWillems** [comment]
Can you elaborate why this is necessary? Wayland CI builds work just fine. So I'm just wondering why this is required and if maybe the CI is wrongly setup.

**Comment by emersion** [comment]
> Wayland CI builds work just fine

They probably just use X11 instead of Wayland. Most Wayland compositors still support X11 clients via Xwayland.

Indeed the CI setup is wrong right now, it builds without Wayland support, see the second commit.

**Comment by SaschaWillems** [comment]
Thanks for letting me know. That's what I actually though.

Your PR is very much appreciated!

**Comment by SaschaWillems** [comment]
CI Builds for Wayland now fail. Can you take a look?

**Comment by emersion** [comment]
Gentle ping :)

**Pull request merged**
