### PR TITLE
Add support for VK_EXT_tooling_info

### PR DESCRIPTION
**Pull request by krOoze**
output might be bit misleading as it would lack the tools from Validation Layers if not enabled.
For the most part probably will be empty unless the driver feels like advertising some nonsense here...

### CODE REVIEW

**Comment by krOoze** [comment]
Seems to work when enabling layers via env:

tooling

**Comment by SaschaWillems** [comment]
Thanks for your PR. Very much appreciated.

Since this is a new kind of information it would make sense to store this in the database, so I would need to add that part.

I'm a bit short in time currently, but I'll take a look at this as soon as possible.

**Comment by krOoze** [comment]
No rush, the SDK is not released, and no drivers report anything here (and most of them probably never will). Also has to be coerced by enabling the layers to show anything.

Though I think the nature of the info is such that it should not be uploaded to DB.

**Comment by SaschaWillems** [comment]
Closing this for now. The caps viewer already checks for tools like the validation layers that could potentially change features and disables uploads.

**Pull request closed without merging**
